# Generated by Django 3.0.4 on 2020-03-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackUser",
            fields=[
                ("slack_id", models.CharField(max_length=128)),
                ("channel_id", models.CharField(max_length=128)),
                ("has_answered_skill_form", models.BooleanField()),
            ],
        ),
    ]
