# Generated by Django 3.0.5 on 2020-04-03 20:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0003_auto_20200401_1327"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("template_file", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="SlackMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actions_block_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "response_url",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "message_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hello.MessageType",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hello.SlackUser",
                    ),
                ),
            ],
        ),
    ]
